/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as BookRouteImport } from './routes/book'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BrunoRouteImport } from './routes/bruno'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaycareRouteImport } from './routes/daycare'
import { Route as DogsRouteImport } from './routes/dogs'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as FoodRouteImport } from './routes/food'
import { Route as GoofyRouteImport } from './routes/goofy'
import { Route as GroomingRouteImport } from './routes/grooming'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as VeterinaryRouteImport } from './routes/veterinary'
import { Route as ServicesIndexRouteImport } from './routes/services.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrunoRoute = BrunoRouteImport.update({
  id: '/bruno',
  path: '/bruno',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaycareRoute = DaycareRouteImport.update({
  id: '/daycare',
  path: '/daycare',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsRoute = DogsRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const GoofyRoute = GoofyRouteImport.update({
  id: '/goofy',
  path: '/goofy',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomingRoute = GroomingRouteImport.update({
  id: '/grooming',
  path: '/grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const VeterinaryRoute = VeterinaryRouteImport.update({
  id: '/veterinary',
  path: '/veterinary',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boarding': typeof BoardingRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/bruno': typeof BrunoRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/daycare': typeof DaycareRoute
  '/dogs': typeof DogsRoute
  '/facility': typeof FacilityRoute
  '/food': typeof FoodRoute
  '/goofy': typeof GoofyRoute
  '/grooming': typeof GroomingRoute
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/updates': typeof UpdatesRoute
  '/veterinary': typeof VeterinaryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boarding': typeof BoardingRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/bruno': typeof BrunoRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/daycare': typeof DaycareRoute
  '/dogs': typeof DogsRoute
  '/facility': typeof FacilityRoute
  '/food': typeof FoodRoute
  '/goofy': typeof GoofyRoute
  '/grooming': typeof GroomingRoute
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/updates': typeof UpdatesRoute
  '/veterinary': typeof VeterinaryRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boarding': typeof BoardingRoute
  '/book': typeof BookRoute
  '/bookings': typeof BookingsRoute
  '/bruno': typeof BrunoRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/daycare': typeof DaycareRoute
  '/dogs': typeof DogsRoute
  '/facility': typeof FacilityRoute
  '/food': typeof FoodRoute
  '/goofy': typeof GoofyRoute
  '/grooming': typeof GroomingRoute
  '/profile': typeof ProfileRoute
  '/training': typeof TrainingRoute
  '/updates': typeof UpdatesRoute
  '/veterinary': typeof VeterinaryRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boarding'
    | '/book'
    | '/bookings'
    | '/bruno'
    | '/contact'
    | '/dashboard'
    | '/daycare'
    | '/dogs'
    | '/facility'
    | '/food'
    | '/goofy'
    | '/grooming'
    | '/profile'
    | '/training'
    | '/updates'
    | '/veterinary'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boarding'
    | '/book'
    | '/bookings'
    | '/bruno'
    | '/contact'
    | '/dashboard'
    | '/daycare'
    | '/dogs'
    | '/facility'
    | '/food'
    | '/goofy'
    | '/grooming'
    | '/profile'
    | '/training'
    | '/updates'
    | '/veterinary'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/boarding'
    | '/book'
    | '/bookings'
    | '/bruno'
    | '/contact'
    | '/dashboard'
    | '/daycare'
    | '/dogs'
    | '/facility'
    | '/food'
    | '/goofy'
    | '/grooming'
    | '/profile'
    | '/training'
    | '/updates'
    | '/veterinary'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardingRoute: typeof BoardingRoute
  BookRoute: typeof BookRoute
  BookingsRoute: typeof BookingsRoute
  BrunoRoute: typeof BrunoRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DaycareRoute: typeof DaycareRoute
  DogsRoute: typeof DogsRoute
  FacilityRoute: typeof FacilityRoute
  FoodRoute: typeof FoodRoute
  GoofyRoute: typeof GoofyRoute
  GroomingRoute: typeof GroomingRoute
  ProfileRoute: typeof ProfileRoute
  TrainingRoute: typeof TrainingRoute
  UpdatesRoute: typeof UpdatesRoute
  VeterinaryRoute: typeof VeterinaryRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bruno': {
      id: '/bruno'
      path: '/bruno'
      fullPath: '/bruno'
      preLoaderRoute: typeof BrunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daycare': {
      id: '/daycare'
      path: '/daycare'
      fullPath: '/daycare'
      preLoaderRoute: typeof DaycareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs': {
      id: '/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof DogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goofy': {
      id: '/goofy'
      path: '/goofy'
      fullPath: '/goofy'
      preLoaderRoute: typeof GoofyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grooming': {
      id: '/grooming'
      path: '/grooming'
      fullPath: '/grooming'
      preLoaderRoute: typeof GroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veterinary': {
      id: '/veterinary'
      path: '/veterinary'
      fullPath: '/veterinary'
      preLoaderRoute: typeof VeterinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardingRoute: BoardingRoute,
  BookRoute: BookRoute,
  BookingsRoute: BookingsRoute,
  BrunoRoute: BrunoRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DaycareRoute: DaycareRoute,
  DogsRoute: DogsRoute,
  FacilityRoute: FacilityRoute,
  FoodRoute: FoodRoute,
  GoofyRoute: GoofyRoute,
  GroomingRoute: GroomingRoute,
  ProfileRoute: ProfileRoute,
  TrainingRoute: TrainingRoute,
  UpdatesRoute: UpdatesRoute,
  VeterinaryRoute: VeterinaryRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
